INSERT INTO blog_posts (`postTitle`, `postDesc`, `postCont`, `postDate`, `postImgPath`) VALUES ("Pack Your Back at CMU", "Pack Your Back is a nonprofit organization that was started in a dorm room in Calkins Hall. It's a few students at CMU who decided that they wanted to be hands on, they wanted to be proactive in helping the younger generation succeed. With that, Pack Your Back was born.", "<p>Pack Your Back is a nonprofit organization that was started in a dorm room in Calkins Hall. It's a few students at CMU who decided that they wanted to be hands on, they wanted to be proactive in helping the younger generation succeed. With that, Pack Your Back was born.</p><p>In January 2016, Galen Miller was volunteering in Flint with his fraternity. As they continued to deliver water and other supplies to the residents suffering from the water crisis, Miller noticed that as the major media outlets began to leave, so did the help.</p><p>That night after the event in Flint, Miller got together a group of friends in his dorm room, and they discussed how they could continue to give back to the community in Flint. They settled on collecting and donating school supplies, as they realized that the water crisis had a massive impact on the development of young school-aged children.</p><p>A group of CMU students and alumni started Pack Your Back in March 2016 and were officially approved as a 501(c)(3) nonprofit in May. They set to work collecting funds and school supplies to donate to the children of Flint and beyond.</p><p>The organization plans to extend to the rest of the state and even the country in the following months and years and already has an expansion plan in place.</p>", "2017-02-07 19:30:34", "assets/blog/bp1/cmu.png");

INSERT INTO blog_posts (`postTitle`, `postDesc`, `postCont`, `postDate`, `postImgPath`) VALUES ("New Year, New Faces, Same Mission", "As the first month of a new year draws to a close, Pack Your back began to work on their 2017 goals. The nonprofit held their first organizational meeting of the year at Central Michigan University on Sunday, January 22nd. ", "As the first month of a new year draws to a close, Pack Your back began to work on their 2017 goals. The nonprofit held their first organizational meeting of the year at Central Michigan University on Sunday, January 22nd. ", "2017-01-29", "assets/blog/bp2/bp2.png");

INSERT INTO blog_posts (`postTitle`, `postDesc`, `postCont`, `postDate`, `postImgPath`) VALUES ("Distribution locations announced!", "Flint and Detroit Public Schools Distribution Events", "<p>Pack Your Back will be holding a school supply distribution on August 6th from 2:00-5:00pm at Mott Community College. This event will take place in the Event Center on-campus.  More information will be posted in the coming weeks regarding this distribution.</
	p<br><p>Pack Your Back will be holding a second distribution event the following week on August 12 from 1:00-5:00pm at the Detroit Public Library.  More information will be posted in the coming weeks regarding this distribution.</p>", "2017-03-14", "assets/icons/bpgeneral.png");

INSERT INTO blog_posts (`postTitle`, `postDesc`, `postCont`, `postDate`, `postImgPath`) VALUES ("Pack Your Back on Ice", "On Thursday, March 23rd, Pack Your Back was excited to host its first annual Midnight Stake. This successful community event was held at the Mount Pleasant Ice Arena.", "Mount Pleasant | On Thursday, March 23rd, Pack Your Back was excited to host its first annual Midnight Stake. This successful community event was held at the Mount Pleasant Ice Arena. It was an enjoyable fundraiser aimed at raising money to buy school supplies for the upcoming summer drives. These two drives will be held in the cities of Flint and Detroit, and hope to supply children with the tools they need to succeed in the classroom. 
Pack Your Back members were able to get to know each other better though this bonding experience. Overall, it strengthened the Pack Your Back community by allowing the organization to reach out to their neighbors at Central Michigan University. In addition to ice staking, students and community members were able to enjoy grilled cheese sandwiches and treats from Insomnia Cookies. 
This was a big event for Pack Your Back, as they hosted over 100 students and community members within the Mount Pleasant area. In total, $550 was raised for the nonprofit. One generous community member even donated a gently used backpack. After this successful fundraiser, the Pack Your Back team looks forward to developing more fun ways to raise funds and connect to their community. “At Midnight Skate, our community came together for a great cause,” Pack Your Back Director of Expansion, Outreach, and Development Joshua Belcher reflected. “Not only did everyone bond, but we helped out kids in need, and we intend to keep helping out kids by bringing everyone together as one", "2017-04-02", "assets/blog/bp3/p2.png");
